### PR TITLE
[Minor] - Updated the gif

### PR DESCRIPTION
**Pull request by MarcoBrunoBR**
# Pull Request Template:

### Describe what you did
Updated the gif

### How you did it
I created a gif and added it in readme

### CODE REVIEW

**Comment by troy0820** [comment]
This is cool, I'll merge this in 👍 Thanks for contributing.

**Comment by MarcoBrunoBR** [comment]
Nice @troy0820

**Comment by qw3rtman** [comment]
Bundling a GIF to the source unnecessarily adds 3 MB to the package size. Additionally, this GIF provides no additional information and shows no additional features as opposed to the old GIF (which is hosted elsewhere, and thus does not add to the package size).

**Comment by troy0820** [comment]
We can slim down the package size honestly by not including the READMEwhich has the gif.  We could put that in the package.json in the `files` section so when published it won't include that. 
or add it to the .npmignore.  I agree that the value for this isn't much, but it makes it easier to maintain because it's not hosted by someone but resident in the repo. @qw3rtman

**Comment by troy0820** [comment]
Nevermind, I just realized that the README is always included regardless of .npmignore or package.json "files" object. 👍

**Comment by MarcoBrunoBR** [comment]
Nice guys. I'm sorry, I didn't know. Thank you for sharing the knowledge :-)

**Comment by qw3rtman** [comment]
No worries, @MarcoBrunoBR! I really do appreciate your willingness to contribute to this project. 😄

**Comment by PabloSichert** [comment]
You can still host that GIF on GitHub pages, though.

**Pull request merged**
