### PR TITLE
Bump version to 2.1.4 (fix #382)

### LINKED ISSUE #382: Version number of 2.1.4 not updated
Looks like the version number in `bin/n` and `package.json` are out of sync:

**bin/n**

```
#!/usr/bin/env bash

#
# Setup.
#

VERSION="2.1.3"
```

**package.json**

```
{
  "name": "n",
  "description": "Interactively Manage All Your Node Versions",
  "version": "2.1.4",
```

### PR DESCRIPTION
**Pull request by danielbayerlein**
Bump version to 2.1.4 - this PR fix #382

### CODE REVIEW

**Comment by sam3d** [comment]
LGTM, it's been over a month why hasn't this PR been merged yet?

**Comment by troy0820** [comment]
This looks good to me 👍 . @qw3rtman I can merge it in if it's okay with everyone.

**Comment by troy0820** [comment]
Thanks for contributing @danielbayerlein 👍.

**Comment by danielbayerlein** [comment]
Thank you!

**Pull request merged**
