### PR TITLE
Replaced --strip with --strip-components

### PR DESCRIPTION
**Pull request by tedgaydos**
Fix for issue #260 where --strip is not recognized.

### CODE REVIEW

**Comment by tedgaydos** [comment]
This got lost when merging everything.

**Comment by maxrimue** [comment]
Shame on me, that means `$GET $url | tar -zx --strip-components=1` in line 445 then right?
I'll get a fix out.

**Comment by maxrimue** [comment]
1.4.1 and 2.0.1 are out, I'm sorry that I missed it.

**Comment by tedgaydos** [comment]
Thank you for pushing this.

**Pull request merged**
