### PR TITLE
add curl --max-time

### PR DESCRIPTION
**Pull request by wangduanduan**
# Pull Request

## Problem

n seems to be stuck after  wait a very long time, finally i found out that curl timeout, i think it will be nice to set a short default timeout for curl

### CODE REVIEW

**Comment by shadowspawn** [comment]
Related: #544

**Comment by shadowspawn** [comment]
There have not been many issues opened about timeouts. I am reluctant to set a custom default when might cause timeouts that given a bit longer might have worked. To some extent we would be picking a value that works for one person.

Would the 5s in the PR be a suitable default for all your curl calls? In which case it could go in default curl config file: https://everything.curl.dev/cmdline/configfile

**Comment by wangduanduan** [comment]
In china , [nodejs.org](http://nodejs.org/) is often inaccessible, which causes us to waste a lot of time trying to troubleshoot the real reason.

Setting up curlrc assumes that the issue is with the network, but it does not necessarily reduce the time spent troubleshooting the problem.

**Comment by shadowspawn** [comment]
Ah right, problem is the node mirror not all use of `curl`.

Another relevant setting which might improve behaviour is using a custom mirror. I haven't heard about how well it is working recently, but it is the example in the README:  https://github.com/tj/n#custom-source

```
export N_NODE_MIRROR=https://npmmirror.com/mirrors/node
```

**Comment by shadowspawn** [comment]
> I am reluctant to set a custom default when might cause timeouts that given a bit longer might have worked. To some extent we would be picking a value that works for one person.

`5 s` is too short. I sometimes see downloads taking 20-30 s. Not sure if the server is sometimes slow, or I get throttled when running lots of downloads for `n` unit tests.

Let us know how the mirror site works.

**Comment by shadowspawn** [comment]
Does using `npmmirror.com` improve your timeout problems @wangduanduan ?

**Comment by wangduanduan** [comment]
yes, it is

**Comment by wangduanduan** [comment]
> Does using `npmmirror.com` improve your timeout problems @wangduanduan ?

Yes, it is

**Comment by shadowspawn** [comment]
Thanks for confirming @wangduanduan 

I think using the country local mirror is a better high-level answer than changing the timeout in this case.

**Pull request closed without merging**
