### PR TITLE
Fix insecure downloading of node-binaries for wget

### PR DESCRIPTION
**Pull request by norpol**
♥

### CODE REVIEW

**Comment by norpol** [comment]
Thank you for bumping and linking to #426.

**Comment by norpol** [comment]
@troy0820 Could you check this out maybe?

**Comment by norpol** [comment]
Not interested in getting this merged anymore.
The only recommendation I would give anyone evaluating whether or not to use `n` is to checkout [nodejs.org](https://nodejs.org/en/download/package-manager/) suggested methods. For example if you need something that is solving similar problems as `n`, checkout [nvm](https://nodejs.org/en/download/package-manager/#nvm) or use your systems package manager (best solution from security aspect).

**Comment by shadowspawn** [comment]
Prerelease available via npm i n@next for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Pull request closed without merging**
