### PR TITLE
prune and bin fixes

### PR DESCRIPTION
**Pull request by ponyspy**
add prune option, based on #407, thanks @sam3d
+ rename prune function
+ fix readme

add version alias, based on #351, thanks @masarakki
+ add lts alias

add lts alias to use option

### CODE REVIEW

**Comment by troy0820** [comment]
I'm going to look at this PR and PR #407 and test it in a container.  This feature looks like it was supposed to land in a previous release.  I do want to give credit to @sam3d and you for making this happen.  Sorry if it feels like I've been neglecting this repo.

**Comment by sam3d** [comment]
@troy0820 No need to apologise! I always think of the article ["My condolences, you’re now the maintainer of a popular open source project"](https://danielbachhuber.com/2016/06/26/my-condolences-youre-now-the-maintainer-of-a-popular-open-source-project/).

**Comment by ponyspy** [comment]
@troy0820 This PR contain all changes from #407 and #351 with small fix from me.

**Comment by troy0820** [comment]
Tested with containers `troy0820/node-n-fedora` and `troy0820/node-n:latest` closes PR #407.  Thanks @sam3d and @ponyspy for the hard work 👍

**Pull request merged**
