### PR TITLE
Added the disabling PaX's mprotect() during an activation.

### PR DESCRIPTION
**Pull request by chrootsu**
This is necessary to copy a flag XATTR_PAX.

### CODE REVIEW

**Comment by maxrimue** [comment]
Sorry, could you provide some more information about what this flag really changes?

**Comment by chrootsu** [comment]
The flag disables mprotect(). This PR corrects an omission in https://github.com/tj/n/pull/228

**Comment by maxrimue** [comment]
I just tried using n with this patch on OS X, and it throws this error for me:
```
n max$ ./bin/n 4.0.0

     install : node-v4.0.0
       mkdir : /usr/local/n/versions/node/4.0.0
       fetch : https://nodejs.org/dist/v4.0.0/node-v4.0.0-darwin-x64.tar.gz
######################################################################## 100,0%
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
   installed : v4.0.0
```

And since this error doesn't occur without this change, there must be something wrong with the patch. Ideas?

**Comment by chrootsu** [comment]
I have no experience with OS X, but it looks like cp has no option --prevent. I'll try to fix it another way.

**Comment by chrootsu** [comment]
@maxrimue Could you check again, please? Now it should work correctly.

**Comment by maxrimue** [comment]
Yep, now it works

**Comment by chrootsu** [comment]
Thank you! ^_^

**Comment by maxrimue** [comment]
No problem :+1:

**Pull request merged**
