### PR TITLE
Support Cygwin & MSYS under Windows

### PR DESCRIPTION
**Pull request by baip**
# Pull Request Template:

### Describe what you did
Support Cygwin & MSYS under Windows

### How you did it
Account for the differences in directory structure and the file type of the installer package.

### How to verify it doesn't effect the functionality of n
The behavior changes only if `uname -a` outputs CYGWIN or MSYS.

### If this solves an issue, please put issue in PR notes.
N/A

### If this solves an issue, please include the output of issue that had problems and then the fixed output from the same command.
N/A

### Squash any unnecessary commits to keep history clean as possible
Done

###  Place description for the changelog in PR so we can tally all changes for any future release
Support Cygwin & MSYS under Windows

### CODE REVIEW

**Comment by troy0820** [comment]
I'm gonna try this code in the environments we support and then release a new version.  This may take some time but I am still looking at this.

**Comment by davidreghay** [comment]
Does this imply support for Git Bash on Windows as well?

**Comment by baip** [comment]
@troy0820 Hi, just wondering if you had a chance to try this out and if there is anything else I can do. Thanks!

@davidreghay Yes, Git Bash on Windows basically wraps MSYS under the cover.

**Comment by shadowspawn** [comment]
I do not have easy access to Windows, so a question in meantime (I wish there was a Windows docker container!).

Does installing node with these changes only update node and npm for Cygwin & MSYS command line, or does it affect cmd and PowerShell too?

**Comment by baip** [comment]
Since WSL came out, I no longer use Cygwin or MSYS. But I thought `n` is a bash program -- how is it supposed to run under CMD or PowerShell?

**Comment by shadowspawn** [comment]
I meant if you change the version of node using `n` under Cygwin, would it affect the version of node and npm for cmd? (I am not sure how much they share search paths.)

**Comment by baip** [comment]
For my old setup, I would install node using `n` under Cygwin and then add the directory to system `PATH`, so yes, in this case, both CMD and Cygwin use the same node installation and changes are shared. But if one doesn't manually add the directory to Windows `PATH` environment variable, then CMD knows nothing about it.

**Comment by shadowspawn** [comment]
Thanks for info @baip 

With WSL available, I am not sure there is enough interest in an `n` running under Cygwin and MSYS  when there are Windows native node version managers available for non-WSL.

I am closing this Pull Request for now, but available for reference if this gets popular.

Thank you for your contributions.

**Pull request closed without merging**
