### PR TITLE
I Added some basic tests via travis yml to make sure it still works as expected

### PR DESCRIPTION
**Pull request by frank-dspeed**
# Pull Request Template:

### Describe what you did
Added Basic Dockerfile for tests and also Production use inside docker
Added .travis.yml to enable this repo inside travis-ci for automated tests on push

### How you did it
i writed into the Dockerfile the needed lines and added also some tests inside .travis.yml

### How to verify it doesn't effect the functionality of n
you can verify that it doesn't affect the functionality of n via n did not change :+1: 

### If this solves an issue, please put issue in PR notes.

solves issue #545 #555

### CODE REVIEW

**Comment by frank-dspeed** [comment]
Closes: #555 #545

**Comment by JohnRGee** [comment]
1) The docker build generates warnings about using `apt` in scripts:

`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

2) I don't think you need both volume mount at runtime and `ADD` at build time. Either will make `n` available in the container.

3) The tests are pretty simple, just testing that node runs after an install, not even that it is the expected version. I don't think it comes close to covering what #545 proposes..

**Comment by frank-dspeed** [comment]
@JohnRGee ok you want to have it test for version no problem you get it :) you want to complain about apt and not apt-get ok you get apt-get :D

**Comment by JohnRGee** [comment]
I offered some feedback on your PR, but you should decide what are worthwhile improvements.

You stated your PR "solves" the issue I opened (#545), and added that this "closes" my issue. I personally disagree. (I still welcome feedback on my own proposal and work, outside this PR.)

**Comment by frank-dspeed** [comment]
@JohnRGee we can simply add every tests that you like i don't have a plan for tests but i looked at your examples and i simply don't understand them :)

i will get this one merged and if you like you can base your tests on this simply remove the bats dependency as this is not needed we can test bash with bash. but i think we need no additional test runner simply a collection of docker run commands should solve all test needs. we can design this commands so that they error.

i also see no need for this proxy stuff and that i never tested something with a proxy in between that adds extra point of error

**Comment by frank-dspeed** [comment]
@JohnRGee you could really help me with some valid test cases in a formart like
- Should return right version when "n latest"
- Should install in directory x when "PREFIX=x n latest"

**Comment by JohnRGee** [comment]
proxy: I made the proxy entirely optional. Why even bother? Big performance boost for running tests locally, with full integration tests that do downloads. I did a check today and my tests ran in 1 min with proxy, 28 min without. node.js was so slow today!

bats: not essential. I wanted to try a test runner and structured tests and focus on the other challenges. Planning ahead for lots of tests.

I like the elegance of your idea of "simply a collection of docker run commands" in theory, but yet to see if it can cope with a variety of tests. A case you may not have considered is running tests on macOS which is not available as a container. (macOS is available on Travis as a host OS.)

I think some important test cases are:
- `n lts` installs expected version of node
- `n latest` installs expected version of node
- `n x.y.z` (explicit version) installs expected version of node
- `n --lts` outputs expected version of node
- `n --latest` outputs expected version of node
- installing with defined N_PREFIX installs to N_PREFIX

At least some (or all) tests should be run with curl and with wget. (Containers to the rescue!)
At least some (or all) tests should be run on MacOS and on Linux.

**Comment by frank-dspeed** [comment]
@JohnRGee i agree on running tests localy but i think still inside docker no one wants to mess up his system only alternativ that i see is using a vm for local testing.

In General i think its ok if we activate travis and then if some one pushes code the tests are running for every pull request and that should be enought for him.

**Comment by shadowspawn** [comment]
@frank-dspeed Do you want to take this any further?

**Comment by shadowspawn** [comment]
Going with #545 approach.

Thank you  for your contributions.

**Pull request closed without merging**
