### PR TITLE
Prevent removing the currently active version of Node.js/io.js

### PR DESCRIPTION
**Pull request by maxrimue**
Solves #292
@tedgaydos is this okay? We have to publish the release drafts before merging this.

### CODE REVIEW

**Comment by tedgaydos** [comment]
There is a function called check_current_version that sets an $active variable to compare. You would also need to move the check in the the while loop. You can remove more than one version at a time.

**Comment by maxrimue** [comment]
@tedgaydos This should be it

**Comment by tedgaydos** [comment]
Got to watch for the possible leading v on the version number. I just tested it with these minor changes below. It looks good. Also remember to change the `VERSION` at the top.

```
local version=${1#v}
[ "${BINS[$DEFAULT]}/$version" == "$active" ] && abort "cannot remove active version ($active)"
rm -rf ${VERSIONS_DIR[$DEFAULT]}/$version
```

**Comment by maxrimue** [comment]
> Also remember to change the `VERSION` at the top.

You mean inside the while loop?

**Comment by tedgaydos** [comment]
The version at the top of the script. 2.0.0. to 2.0.2.

**Comment by maxrimue** [comment]
@tedgaydos Publish the releases and we can merge

**Comment by tedgaydos** [comment]
Please add the $active in the abort like in my example. I believe it will help increase the feedback to the user. They will see which version is active without needing to type extra commands..

**Comment by maxrimue** [comment]
Finally, that should be it now :smile:

**Pull request merged**
