### PR TITLE
feat(docs): add shell syntax highlighting

### PR DESCRIPTION
**Pull request by mesqueeb**
# Pull Request
## Problem

No shell syntax highlighting in readme.

## Solution

Add shell syntax highlighting in readme.

### CODE REVIEW

**Comment by shadowspawn** [comment]
I had used indentation code code blocks mainly because it was cleaner for editing, but worth considering changing as the viewing matters more than the editing.

The syntax highlighting I see in README for https://github.com/mesqueeb/n/tree/patch-2 is a bit underwhelming. I see `export` in colour in the examples near the end, but also false-positive highlights for `select` and `return` and `exec` and `test` in other code blocks. I am not seeing a lot of value in the highlighting? (I assume the syntax highlighting does not vary much by browser. I did check with both Safari and Chrome.)

I did some reading and see `ShellSession` (aka console) suggested for command-line interactions, as opposed to actual shell scripts.

- https://stackoverflow.com/a/49004070/1082434
- https://github.com/github/linguist/blob/master/vendor/README.md

**Comment by shadowspawn** [comment]
I tried `ShellSession` and not sure what the rules are, but mainly see a colour difference between lines starting with $ and those without. I have been following a `markdownlint` suggestion to only use $ when also showing the output, so simply using `ShellSession` without changing the code blocks does not work very well.

https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md014

**Comment by mesqueeb** [comment]
@shadowspawn I really enjoy that comments behind `#` are light grey, so it's easy to differentiate comments from commands.
the rest I don't mind so much.

**Comment by shadowspawn** [comment]
I like the comments too. If you just change that one, I'll merge.

**Pull request closed without merging**
