### PR TITLE
Remove old io project support

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request Template:

### Describe what you did

Removed old iojs from code and help.

### How you did it

Removed old iojs support from code, and old iojs examples from command-line help and README.

### How to verify it doesn't effect the functionality of n

$ n 8.0.0

     install : node-v8.0.0
       mkdir : /usr/local/n/versions/node/8.0.0
       fetch : https://nodejs.org/dist/v8.0.0/node-v8.0.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v8.0.0

Bagheera:n john$ n lts

     install : node-v8.11.3
       mkdir : /usr/local/n/versions/node/8.11.3
       fetch : https://nodejs.org/dist/v8.11.3/node-v8.11.3-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v8.11.3

$ PROJECT_NAME="iojs" PROJECT_URL="https://iojs.org/dist/" n project latest

     install : iojs-v3.3.1
       mkdir : /usr/local/n/versions/iojs/3.3.1
       fetch : https://iojs.org/dist/v3.3.1/iojs-v3.3.1-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v3.3.1

$ n bin 8.0.0
/usr/local/n/versions/node/8.0.0/bin/node

$ n use 8.0.0 --version
v8.0.0
 
### If this solves an issue, please put issue in PR notes.

Resolves issue #331

### If this solves an issue, please include the output of issue that had problems and then the fixed output from the same command.

Remove old iojs support from help and code.

###  Place description for the changelog in PR so we can tally all changes for any future release

### CODE REVIEW

**Comment by JohnRGee** [comment]
I have resolved the merge conflict with updated master using the GitHub interface.

**Comment by williamkapke** [comment]
I use this to get the nightly build for [node.green](https://node.green):
> LATEST=$(curl -sL https://nodejs.org/download/nightly/index.tab |   awk '{ if (!f && NR > 1) { print $1; f = 1 } }')
PROJECT_NAME="node" PROJECT_URL="https://nodejs.org/download/nightly/" n project $LATEST

This change broke that. Is there something new or better way of doing it?

I've been forcing version 2.1.7 since this change- would love to run a newer version.

See: https://github.com/williamkapke/node-compat-table/blob/gh-pages/test.sh#L6

**Comment by shadowspawn** [comment]
@williamkapke 
(I have node.green bookmarked as my go-to site for checking feature compatibility with older versions of node. ❤️ )

The nightly builds have been explicitly supported since `n` v6. For your use case, simply:
```
n nightly
```

A longer example to match against your previous scripting:
```
$ curl -sL https://nodejs.org/download/nightly/index.tab | awk '{ if (!f && NR > 1) { print $1; f = 1 } }'
v15.0.0-nightly20200801cc7ec889e8

$ n ls-remote nightly
Listing remote... Displaying 20 matches (use --all to see all).
15.0.0-nightly20200801cc7ec889e8
15.0.0-nightly20200731dc00a07426
15.0.0-nightly202007301fe39f0b4b
15.0.0-nightly20200729360bf9b289
15.0.0-nightly202007286fd09e4f36
15.0.0-nightly20200727db54b57042
15.0.0-nightly2020072631ba9a20bd
15.0.0-nightly20200725de192246bc
15.0.0-nightly20200724d1e4e8eaba
15.0.0-nightly2020072341c1e72b76
15.0.0-nightly20200722b0b52b2023
15.0.0-nightly202007212c05beeb54
15.0.0-nightly202007190c81cadec6
15.0.0-nightly202007187a447bcd54
15.0.0-nightly20200717bf0d82c102
15.0.0-nightly20200716d46fc91be4
15.0.0-nightly202007153b130327fa
15.0.0-nightly20200714c7627da837
15.0.0-nightly20200712ac6ecd6b7f
15.0.0-nightly20200711c176d5fac2

$ n nightly

  installing : nightly-v15.0.0-nightly20200801cc7ec889e8
       mkdir : /usr/local/n/versions/nightly/15.0.0-nightly20200801cc7ec889e8
       fetch : https://nodejs.org/download/nightly/v15.0.0-nightly20200801cc7ec889e8/node-v15.0.0-nightly20200801cc7ec889e8-darwin-x64.tar.xz
   installed : v15.0.0-nightly20200801cc7ec889e8 (with npm 6.14.7)
```

**Comment by williamkapke** [comment]
🤦 Aaaahh the problem is that it was made TOO easy and I was looking for something hard! haha

Thanks for the help. Glad node.green has been useful for you!! It has always used `n` and would exist without it. (seriously, I couldn't get any other version manager working on Heroku)

**Pull request merged**
