### PR TITLE
Remove prev, iojs alias, add quiet mode and more.

### PR DESCRIPTION
**Pull request by tedgaydos**
Some changes to the script, readme file and package.json file.

- Pulled `prev` from the script and documentation as discussed in issue #184.
- Pulled the `iojs` alias from the script and documentation because it never worked as described in issue #255.
- Added a quiet mode option (`-q` or `--quiet`) for curl to not display the progress bar as requested in issue #205.
  - Fixed a "bug" in the `install` function where curl was hard coded to get the tarball instead of what is set in the GET variable.
  - I also moved the call to `tarball_url` in the `install` function below the test for an already installed version. It is a waste to build the url every time and not use it.
- I pulled documentation for `n io stable` and `n io --stable` but they still work. They actually work correctly now for `io` by always calling latest. This was brought up in issue #230 and I sat on it for a bit. I decided that this would be best for now because it provides backward compatibility.

I also added some minor items from other PRs:
#241 - Added Gitter badge
#239 - Calling `n bin` would not advance the shell prompt to a new line. I just switched `printf` to `echo`.

One final item I pulled is the `node` keyword which called `set_default`. It looks like noise because the default state for `n` would be to install node. I also need the keyword for a feature request in issue #185. To preserve script state I had to add separate functions to install latest and stable so it remembers which mirror to use.

And as @tjwebb said in issue #184 the version was changed to 1.4.0 in the script and package.json files. Or should it be 2.0.0? And if we go to version 2.0.0, maybe I should just make calls to `n io (--)stable` abort?

### CODE REVIEW

**Comment by maxrimue** [comment]
:+1: Looks good!
I think we should go to 2.0.0 since these changes are "incompatible API changes" and therefore are major changes.

**Comment by tedgaydos** [comment]
Just updated the PR. Put version to 2.0.0 and using `n io stable' or 'n io --stable' will now abort and report an error because it is not a supported command anymore..

**Comment by knownasilya** [comment]
Can we pull out `--quiet` into a separate PR so it can get in quicker (before major bump)?

**Comment by tedgaydos** [comment]
@tjwebb I merged upstream to clear any conflicts. What is your take on this PR?

**Comment by tjwebb** [comment]
I wish it were only one feature. It'll take a little awhile to review

**Comment by troy0820** [comment]
Are we jumping from 1.3.0 to 2.0.0?

**Comment by maxrimue** [comment]
@troy0820 If we really modify n that much, we should
@tjwebb Is there any progress on the review btw?

**Comment by knownasilya** [comment]
I say split it out into several PRs, ones that require a major bump and ones that don't.

**Comment by tjwebb** [comment]
@tedgaydos  yea as I mentioned, a PR should contain one thing. No progress on the review, haven't had time. It'll be easier to review if it were multiple PRs, and I agree with @knownasilya

**Comment by qw3rtman** [comment]
This is a major API change. If we merge these changes, we should update to 2.0.0. :+1:

**Comment by troy0820** [comment]
I agree with @knownasilya and @tjwebb. Multiple pull requests that can eventually push this to 2.0.0.

**Comment by tedgaydos** [comment]
I will break it up tonight.

**Comment by tedgaydos** [comment]
Everything is in separate PRs now. See #267, #268, #269, #270, #271

**Comment by knownasilya** [comment]
@tedgaydos very nice!

**Comment by tedgaydos** [comment]
@knownasilya Thanks. This is a cool little script. I am very grateful to be able to contribute.

**Comment by tedgaydos** [comment]
@tjwebb It is separated into new PRs. I am closing this one.

**Pull request closed without merging**
