### PR TITLE
Refactor script based on ShellCheck suggestion

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Refactor the `n` script, based on my Shell Script experience and [ShellCheck](https://github.com/koalaman/shellcheck/) suggestion.

### CODE REVIEW

**Comment by JohnRGee** [comment]
I initially thought this might be a wild style change request, but when I looked into ShellCheck I was impressed by the depth and accuracy of the advice. Thanks @PeterDaveHello.

I am willing to do a formal review of the PR if helpful to maintainers.

**Comment by PeterDaveHello** [comment]
Any chance to move forward here, it started to have conflicts here, I'd like to resolve it if we can do something here ;) Thanks.

**Comment by shadowspawn** [comment]
I have recently been added as a maintainer. I am interested in making these changes, but do not want to take it as a Pull Request (sorry). I would like to work through the changes suggested by ShellCheck myself so I can check each change and do it incrementally. (I have done this once already on my own fork of n, inspired by this Pull Request.)

I don't want you to miss out on getting credited as a contributor though, if that matters to you. You could submit a new Pull Request with a single or small change, and could say in the commit message it is a small example of wider changes recommended?

**Comment by PeterDaveHello** [comment]
@shadowspawn changes are separated now, should be good enough?

**Comment by shadowspawn** [comment]
I have cherry-picked all but one of the commits into `develop` branch for next release.

(I left out "Declare and assign separately to avoid masking return values" as not currently testing the return values.)

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by shadowspawn** [comment]
Shipped in v4.0.0

**Pull request closed without merging**
